### ISSUE TITLE
Chỉnh sửa lại phần buy x get y trong tab conditions của cataglog rule

### ISSUE THREAD

**Issue by blankapham** [htmyheart/magento-development#12]
https://prnt.sc/jouqg7

**Comment by tudn9x** [comment]
### Tasks:
- [x] Show in backend
- [x] Add product after
- [x] Process for gift
- [x] Process gift on slide
- [x] Process gift when update cart
